### ISSUE TITLE
I cant change background

### ISSUE THREAD

**Issue by Sergiu15155** [parsec-cloud/Parsec-Cloud-Preparation-Tool#39]
Help me pleaseee

**Comment by AhmedHalat** [comment]
Sorry for the late reply.
His scripts actually disable the ability to change the background.
If you want to be able to change it, try running the tool from my [forked repo](https://github.com/AhmedHalat/Parsec-Cloud-Preparation-Tool)

**Comment by AhmedHalat** [comment]
My repo is exactly the same, I just reenabled the ability to choose your own wallpaper. It should solve the issue

**Comment by jamesstringerparsec** [comment]
Addressed in readme update
