### ISSUE TITLE
How would do I remove the 1 hour warning script?

### ISSUE THREAD

**Issue by Liucid** [parsec-cloud/Parsec-Cloud-Preparation-Tool#40]
First of all, thanks so much for making this. It was incredibly easy to set up. I really appreciate your work.

I'd like to remove the 1 hour warning script. Would you be able to advise on how to do that? Thank you.

Jia

**Comment by jamesstringerparsec** [comment]
You can delete the task from task scheduler, it's called "One Hour Warning Message"
