### ISSUE TITLE
Nvidia drivers update

### ISSUE THREAD

**Issue by CyberMew** [parsec-cloud/Parsec-Cloud-Preparation-Tool#42]
I am using Google Cloud compute with Nvidia Tesla T4.

I installed this tool several weeks ago, and it prompted me to install some Nvidia drivers, which I did. 

Now that I want to update the driver to the latest 451.48, do I have to use the tool again or is there a manual way for me to update it in the proper way? Or is that only available for latest generation of RTX nvidia cards?

update: found this link https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-450-51-05/index.html, am I suppose to download and run this on my Windows Server 2019? I can't find the download either..

**Comment by jamesstringerparsec** [comment]
You need to wait until Google Cloud releases a licensed virtual workstation driver for the T4 instance.

The latest driver they currently offer is 432.44.

Cloud GPU drivers aren't free like GTX / RTX NVIDIA consumer drivers, and Google has to do special work to make them available for their own cloud provider instances.  

I believe AWS G4DN instances have much more recent driver versions, so if you want to play Warzone or whatever you can try switch to AWS.

**Comment by CyberMew** [comment]
Thanks for the information. I saw this:

https://cloud.google.com/compute/docs/gpus/grid-drivers-table

Does it mean I can download and install those versions?

**Comment by jamesstringerparsec** [comment]
Yea try the first windows driver listed, starting with grid11.0, if it
works let me know.

You can just copy the URL and download it to the machine and install it.

Test that it allows you to select 3840x2160 in the nvidia control panel.

**Comment by CyberMew** [comment]
Just tried, the first time it restarted to a black screen and didn’t load properly so I reset it and it was able to restart fine. So far so good. The only issue I have now is Parsec not setting the resolution to low and is stuck to the highest resolution.
