### ISSUE TITLE
impossible d'utiliser le scripte sur un serveur dedier hetzner

### ISSUE THREAD

**Issue by URKAhub** [parsec-cloud/Parsec-Cloud-Preparation-Tool#43]
j'ai ressemant acquis un serveur dédier chez hetzner comportant un I7 7700, 64go de ram et une Nvidia GTX 1080 et étant sous Windows serveur 2019 standard. problème, parsec ne fonctionnais pas donc je suis aller voir sur le discord et l'on ma conseiller d’exécuter ce script. seul problème, la GTX 1080 n'est pas compatible. (un screen de l'erreur : `https://cdn.discordapp.com/attachments/482535179974606859/736200373512962058/unknown.png` )
Maintenant je me retrouve avec un serveur disponible uniquement par RDP et qui ne fait même plus tourner mes jeux (comme Fortnite par exemple).
Serais t-il possible de faire une update pour permettre la connexion depuis serveur dédier ? et d'ajouter une fonctionnalité de retour en arrière en cas d'erreur ? 
Cordialement URKA.

**Comment by badjware** [comment]
Je ne suis pas un développeur de ce script, mais je suis familier avec son utilisation. Le script qui affiche l'erreur est l'installateur les pilotes de carte graphiques de centre de données. Comme vous utilisez une instance avec une carte graphique "standard", vous pouvez simplement ignorer ce message et télécharger les pilotes sur le site officiel de Nvidia.

Prenez notes que seul AWS, Azure, Paperspace et Google sont supportés, Hetzner n'est pas officiellement supporté donc il n'y a aucune garantie que le script fonctionne ou que le mainteneur ajoute le support.

À l'avenir, je vous recommande fortement de poster en anglais sur github, la majorité des personnes ici sont anglophone.

**Comment by URKAhub** [comment]
EN : well, excuse me, I should have used a translator first. So hetzner not being supported, the script made my server totally unusable to run a game. I cannot completely re-install it so I would like to know if it was possible to uninstall the script in order to return to the original state
FR : bien, excusez moi, j'aurais du commencer par utiliser un traducteur. Donc hetzner n’étant pas pris en charge, le script a rendu mon serveur totalement inutilisable pour exécuter un jeux. il m'est impossible de le re-installer complètement alors j'aimerais savoir si il était possible de désinstaller le script afin de revenir a l'etat d'origine

**Comment by jamesstringerparsec** [comment]
@URKAhub There is no script to return it to the original state.  I am doubtful the machine is in a non recoverable state due to my script.

If you want to use Hetzner, you need to pay their fee for headless HDMI dongle.

Thanks for your help Badjware
