### ISSUE TITLE
Still not able to connect to the host screen

### ISSUE THREAD

**Issue by gtaski** [parsec-cloud/Parsec-Cloud-Preparation-Tool#44]
I've basically installed everything, I've read the instructions, No errors or anything, But when I try to connect, it says I can't connect for some reason, Please help me out thanks!

**Comment by devporter007** [comment]
What error code parsec gives you?

**Comment by jamesstringerparsec** [comment]
Closing - this issue isn't related to the script, but instead related to Parsec.  For Parsec support issues consult the Discord or support site.
