### ISSUE TITLE
Custom resolution issue

### ISSUE THREAD

**Issue by batmacumba** [parsec-cloud/Parsec-Cloud-Preparation-Tool#45]
Hello, first I want to say this is a really good tool. I've been gaming for a few months with it, thanks a lot!

Here's my environment:
Host: AWS G4dn with NVidia T4
Client: MacBook Pro with 1440x900 display

The issue is that I can't find a way to make Parsec stream to my client at the native resolution (1440x900). That resolution is not available on the dropdown menu, and when I connect with "Use client resolution" option it just resizes to 1366x768. I have tried everything, including NVidia control panel, Custom Resolution Utility, all. It's as if the "Virtual Display" Parsec is connected to won't support that resolution. When I connect via RDP it's automatic, everything works. 

I´m asking here because I feel this issue is connected to the NVidia driver installed, or to the "Generic PnP monitor" created. Is there any way to make this "monitor" stream at the desired resolution? Thanks!

**Comment by jamesstringerparsec** [comment]
You're out of luck I'm afraid, if the driver doesn't support custom resolutions either by the NVIDIA Control Panel or via Custom Resolution Utility.. there is nothing you can do.

**Comment by batmacumba** [comment]
> You're out of luck I'm afraid, if the driver doesn't support custom resolutions either by the NVIDIA Control Panel or via Custom Resolution Utility.. there is nothing you can do.

Would you be able to tell me which driver doesn´t support this custom resolution? I suppose it´s not NVIDIA, as owners of regular PCs can use 1440x900. Are you talking about the "Generic PnP" driver? Thanks
