### ISSUE TITLE
Could you specifiy IAM Role configuration for AWS Access Key

### ISSUE THREAD

**Issue by chris42** [parsec-cloud/Parsec-Cloud-Preparation-Tool#46]
Hi there, 
The preparation tool is asking for an aws key to access nvidia-gaming.s3.amazonaws.com ?

I am not sure how I could handle permissions for a bucket not in my possession? Could you please specify which roles are needed for the Key? Best give a configuration example?

Thanks

**Comment by jamesstringerparsec** [comment]
You're best off reading the documentation https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html#nvidia-gaming-driver

**Comment by chris42** [comment]
To be helpful to others, this is probably the important part (might also be something for the howto?):
"IAM users must have the permissions granted by the AmazonS3ReadOnlyAccess policy"

Alternatively you can use the NVIDIA Gaming PC AMI from Marketplace. Which works fine with the Parsec scripts and you do not need to provide an AWS Key as drivers are already installed.
