### ISSUE TITLE
Resolution stuck at 1366x768

### ISSUE THREAD

**Issue by H3adcap** [parsec-cloud/Parsec-Cloud-Preparation-Tool#49]
NO matter what i do, update drivers, delete the persistent routes, the resolution does not change, the machine sees 2 displays,(on AWS EC2 image)

**Comment by Taapo** [comment]
Exactly the same problem. I cannot get the specified 4K resolution. g4dn.xlarge instance.

**Comment by jamesstringerparsec** [comment]
Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Cloud-GPU-Updater/master/GPUUpdaterTool.ps1
Open %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.
Save the file (do not Save As)
Run GPU updater tool on the desktop
