### ISSUE TITLE
Client desktop is showing wrong display resolution + no icons

### ISSUE THREAD

**Issue by sayaknaiya** [parsec-cloud/Parsec-Cloud-Preparation-Tool#50]
After installing the script , when I am opening through parsec , it's opening. But it's not showing any desktop icons. Even when I click any icons present in bottom of the screen (cortana icon, windows icon) it's not showing anything. Something is happening in background, but I am not seeing anything. 

1. I have disabled windows default display
2. I am working on Aws 

Please help... @steventhegeek

**Comment by jamesstringerparsec** [comment]
Terminate the instance and start again from the beginning, I updated the code.

**Comment by sayaknaiya** [comment]
Thank you so much..
