### ISSUE TITLE
AWS g4dn.xlarge Ultrawide Resolution + Parsec

### ISSUE THREAD

**Issue by seffignoz** [parsec-cloud/Parsec-Cloud-Preparation-Tool#52]
Trying very hard to get my AWS instance (g4dn.xlarge) to accept ultrawide aspect-ratio (3440 x 1440), i used the Parsec Cloud Preparation tool, but somehow, ultrawide resolution doesnt show up, nor does it allow me to create a custom resolution (greyed out). 

I tried reinstalling the NVIDIA drivers, which didn't help. Also tried creating another instance which also didnt fix it. Somehow I'm stuck with the black bars on both sides of the screen because the aspect ratio is locked... 

I also tried to connect to a friend that has Ultrawide resolution set up, and parsec server, and it works fine (so it's definitely not a Parsec issue)

Anyone has a fix for this?

**Comment by jamesstringerparsec** [comment]
If you are a Parsec Warp or Parsec for Teams user you can enable virtual displays which include this resolution.
