### ISSUE TITLE
PostInstall.ps1 fails to download from builds.parsecgaming.com

### ISSUE THREAD

**Issue by BirkhoffLee** [parsec-cloud/Parsec-Cloud-Preparation-Tool#54]
```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At C:\Users\user\Desktop\parsectemp\PostInstall\PostInstall.ps1:467 char:5
+     (New-Object System.Net.WebClient).DownloadFile("https://builds.pa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

This is the same to https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/issues/14. Apparently

```
[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls" 
```

needs to be put in `PostInstall.ps1` instead of the initial command.

**Comment by BirkhoffLee** [comment]
Note: this was run on GCP, Windows Server 2016

**Comment by powext** [comment]
Same

**Comment by patriciodavila** [comment]
same

**Comment by jamesstringerparsec** [comment]
I didn't get this error under Server 2019, perhaps Server 2016 is different

**Comment by jamesstringerparsec** [comment]
I added this based on your feedback, I didn't experience it myself however.

**Comment by powext** [comment]
I tested multiple instances in the last few weeks, on GCP and AWS, and only in W16 server machines the script breaks

**Comment by jamesstringerparsec** [comment]
Most likely to WS16 default TLS level being too low, I guess they set WS19 to a more reasonable level.
