### ISSUE TITLE
support for g4ad instances

### ISSUE THREAD

**Issue by Anntoin** [parsec-cloud/Parsec-Cloud-Preparation-Tool#55]
https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-new-amazon-ec2-g4ad-instances-powered-by-amd-radeon-pro-v520-gpus/

They just need the AMD driver https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-amd-driver.html

Tried one out manually installing the driver and seems to work well with parsec

**Comment by jamesstringerparsec** [comment]
Given how underwhelming AMD encoder performance is in my experience of working at Parsec I'm not in a huge rush to add this, but for now as you said users can install their own drivers, but don't expect great encoder performance over 1080P.

**Comment by korjaa** [comment]
I'm getting encode time of ~3.5 ms with g4ad.x4 . What kind of underwhelming performance you mean @jamesstringerparsec?
![2021-01-02-150217_677x69_scrot](https://user-images.githubusercontent.com/13328062/103457895-ad282380-4d0b-11eb-8a01-f6dea0da9c98.png)

**Comment by jamesstringerparsec** [comment]
3840x2160 H265 with a full screen video playing on the host will typically perform poorly with AMD encoders.
