### ISSUE TITLE
Running script in Google Cloud

### ISSUE THREAD

**Issue by patriciodavila** [parsec-cloud/Parsec-Cloud-Preparation-Tool#56]
After running script and selecting 'y' for auto logon I get this:

Auto Logon Configured
Install-WindowsFeature : The request to add or remove features on the specified server failed.
Installation of one or more roles, role services, or features failed. Error: 0x80240438
At C:\Users\parsectestuser\Desktop\parsectemp\PostInstall\PostInstall.ps1:486 char:5
+     Install-WindowsFeature Net-Framework-Core | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Vhd=; Credent...Name=localhost}:PSObject) [Install-WindowsFeature],
    Exception
    + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWind
   owsFeatureCommand
New-ItemProperty : The property already exists.
At C:\Users\parsectestuser\Desktop\parsectemp\PostInstall\PostInstall.ps1:790 char:5
+     New-ItemProperty -path HKCU:\Software\Microsoft\Windows\CurrentVe ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (HKEY_CURRENT_US...rentVersion\Run:String) [New-ItemProperty], IOExcepti
   on
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.NewItemPropertyCommand

autologin : The term 'autologin' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\parsectestuser\Desktop\parsectemp\PostInstall\PostInstall.ps1:699 char:13
+             autologin
+             ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (autologin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Auto logon doesn't actually work after this. Still need to login with RDP then with Parsec.
Any advice would be appreciated!

**Comment by jamesstringerparsec** [comment]
Sounds like you didn't create a Windows Server 2019 Datacentre Desktop Experience instance?

**Comment by jamesstringerparsec** [comment]
Closing until issue opener replies to my comment.

**Comment by patriciodavila** [comment]
I thought I had (either 2016 or 2019 Windows Server); I'll keep at it. Thanks!

**Comment by jamesstringerparsec** [comment]
Please try again with Windows Server 2019 Datacentre Desktop Experience
