### ISSUE TITLE
Unattended setup

### ISSUE THREAD

**Issue by rix0rrr** [parsec-cloud/Parsec-Cloud-Preparation-Tool#59]
I'd like to make a CloudFormation/CDK script to set up a Parsec gaming machine on AWS from scratch. We can run commands on fresh machines using Systems Manager.

These scripts are great, but right now all the Y/N prompts make it so that user interaction is required, so the machine can't be completely started from nothing.

Could you add an option that just assumes `Y` for all prompts?

(I'd love to help out but I have literally zero experience with PowerShell)

**Comment by jamesstringerparsec** [comment]
This is probably the wrong approach.  You should instead look at building your own AMI, which would be much higher performance from a time to launch perspective, and requires no work on my behalf.

Just note that Parsec requires a commercial license if you are intending to use this in your organization.

**Comment by rix0rrr** [comment]
My motivation for the request was https://github.com/rix0rrr/kessel-run.

You seem to be under the apprehension that I'll be rolling this out inside my company. That's not my motivation, I'm just thinking about my future self and also thinking about saving AWS costs.

I'd like to be able to throw away the current gaming instance I've got going, and be safe in the knowledge that I'll be able to recreate one from scratch in the future in a couple of minutes.

The reason I'm wouldn't want to go for an AMI here is that the AMI is still going to cost me for storage.
