### ISSUE TITLE
AutoLogon doesn't work on Windows 2019 Full Base

### ISSUE THREAD

**Issue by rix0rrr** [parsec-cloud/Parsec-Cloud-Preparation-Tool#61]
I've just run the scripts on a fresh AWS Windows 2019 Full Base image (ami-01819d85044afd4c6).

The script does prompt me for my username and password when it says it's going to configure Automatic Logon, but upon reboot the automatic logon doesn't work.

When I look at the registry the required entries aren't there.

Is there a way to just run the automatic logon part of the script to debug this issue?

**Comment by rix0rrr** [comment]
(Can repro using this: https://github.com/rix0rrr/kessel-run)

**Comment by rix0rrr** [comment]
Is it because [`Set-AutoLogon`](https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/blob/be4ff4b047545cb1244067e7f9176edebdf6a835/PostInstall/PostInstall.ps1#L277)

is actually never called from neither

* [PromptAutoUserLogon](https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/blob/be4ff4b047545cb1244067e7f9176edebdf6a835/PostInstall/PostInstall.ps1#L368)
* nor [GetInstanceCredential](https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/blob/be4ff4b047545cb1244067e7f9176edebdf6a835/PostInstall/PostInstall.ps1#L318)

?

**Comment by jamesstringerparsec** [comment]
Please try now, by copying the code from the readme into Powershell again

**Comment by rix0rrr** [comment]
Yep https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/commit/7a76c272140ad03968dae57399f0b22202bc5309 fixed it

**Comment by rix0rrr** [comment]
Oh wait, I think this might have introduced another bug. If I type the password incorrect and retry, the `Set-AutoLogon` gets executed twice:

![image](https://user-images.githubusercontent.com/524162/103374194-36a2e000-4ad7-11eb-8759-f3e22d7e624d.png)

**Comment by rix0rrr** [comment]
Also, I'm not sure if I made this typo the first time or the second time, but a typo ended up in my registry:

![image](https://user-images.githubusercontent.com/524162/103374293-7e296c00-4ad7-11eb-9276-93b886075c47.png)

**Comment by rix0rrr** [comment]
It's probably because of the recursion. How about a simple loop like:

```
Function GetInstanceCredential {
    While ($true) {
        $Credential = Get-Credential -Credential $null
        TestCredential -Credential $Credential 
        Set-AutoLogon -Credential $Credential
        Return
    } Catch {
        $Answer = Read-Host "Retry? (Y/n)"
        Switch ($Answer) {
            N {
                Return
            }
        }
    }
}
```

(Combined the two `Try`s as well since they seem to be doing the same thing, roughly...)

**Comment by jamesstringerparsec** [comment]
Thanks for the detailed bug report and sample code, I'm on vacation at the moment but I fixed the issue, unfortunately your code sample didn't handle the exceptions correctly, so I just added some checks inside my function to remove the variable if there is an exception, as well as only running set-autologon if there is a credential variable present.  Seems to work reliably for now.

**Comment by jamesstringerparsec** [comment]
Is this fixed? @rix0rrr

**Comment by rix0rrr** [comment]
I did not test it anymore. I trust you did :)
