### ISSUE TITLE
AWS G4DN - resolution stuck to large, can't change

### ISSUE THREAD

**Issue by alxpereira** [parsec-cloud/Parsec-Cloud-Preparation-Tool#62]
Hello, 

I have a quite random behavior on my G4DN host + parsec when streaming to my Macbook Pro (13,3-inch (2560 x 1600)). 
At first, it looks like the resolution is quite right but then after loading X or Z (steam, or an another software) it changes the resolution on the host side and then... stuck. Impossible to change it back (using both Nvidia Panel or Parsec Button Menu doesn't nothing). 

I'm on AWS (ap-northeast-1). No problem when installing parsec with the Powershell script. Games are well too. Just the screen scale makes me crazy...

Any idea ?

Thx !

**Comment by aaweb** [comment]
Similar issue here where it is stuck at 3840 x 2160 and can't be changed in Display Settings nor Nvidia settings. 

Any ideas? Thanks a lot

**Comment by alxpereira** [comment]
Found a few reasons linked to this : 

- Oculus Rift Setup (I was playing VR through Steam VR + Virtual Desktop) is messing with resolution. In my latest installs, I just didn't run it before playing my steam games (just installed, never run after install) and it looks running properly for now.

- Latest version of AMI + Nvidia Drivers looks more stable. Didn't get this pb on my latest install (no VR setup). 

Let's see...
