### ISSUE TITLE
404 Download Issue - Post Install

### ISSUE THREAD

**Issue by designzoo-adrian** [parsec-cloud/Parsec-Cloud-Preparation-Tool#64]
I am receiving a 404 download issue on the following download ref in the PostInstall script.

https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

The file does appear to be missing. What will this affect?

<img width="1168" alt="Screenshot 2021-01-28 at 17 18 28" src="https://user-images.githubusercontent.com/1336717/106174414-ecbc2100-618c-11eb-9a1c-653e4c1f234b.png">

**Comment by jamesstringerparsec** [comment]
Also by removing that Xbox 360 driver, it renders controllers unusable on Server 2019

**Comment by designzoo-adrian** [comment]
Can this in short term be remedied by changing the download references to alternative s3 locations like some of the other file refs VS the official windows download site that the file has been removed on. Does anyone have local file copies of these files? 

Also are there alternate controller drivers that could be investigated or implemented into the code base that would integrate with parsec.

I’m happy to contribute here to active changes or future support. The cloud server solution for parsec for what I’m using it for as a business is essential, lack of controller support would be a big pain.

**Comment by jamesstringerparsec** [comment]
I recommend transitioning to a Windows 10 image rather than Server 2019.  These typically aren't licensable inside of GCP or AWS, but Azure has them, otherwise you can BYO license and image.  In that case this script probably isn't required either.

**Comment by ckuma** [comment]
FWIW, here's my experience on AWS with Win Server 2019. I do not encourage anybody to follow these steps unless they feel confident that they know what they're doing and responsible for any incorrect executable they'd download along the way, as I do not control the links that I'm giving out. The bottom line is that I got from 0 to a working setup yesterday (Jan 30th 2020) using Win2019 server.

I was able to get the whole thing setup by finding each of the executables "on my own", and here are the parts where I encountered issues:  
- Downloaded the DirectX redist from a couple sources ([this one](https://community.pcgamingwiki.com/files/file/2106-legacy-directx-sdk-redist-directx_jun2010_redistexe/) and [that one](https://drive.google.com/file/d/0BzObCxIexAk9VGUycmdnc1MxTlk/view)) and ran virustotal scans for each (which, for anyone willing to risk downloading random exes from the web is really a bare minimum..) and found no issue with the exes and complete similarity, so I installed one manually and removed from the script any step related to downloading or running the dx executables  
- .NET 3.5 didn't download/install for me but following [this guide](https://support.solarwinds.com/SuccessCenter/s/article/Install-NET-3-5-on-Windows-Server-2019?language=en_US) manually worked
- [ViGEmBus](https://github.com/ViGEm/ViGEmBus/releases) also didn't work through the script (although the release notes indicate support for Win10 only the [issues confirm Win2019 server works](https://github.com/ViGEm/ViGEmBus/issues/69)) so I installed it manually 
- Using a Xbox 360 controller led to a "driver not found" for the virtual device upon plugging, which led me to search for (and find) the elusive `Xbox360_64Eng.exe` which *does* work once installed manually (piece of advice: the executable is on websites I do not feel deserve sharing, and recommend that users trying to get through the download procedure of such exe should have an ad-blocker, watch out for unnecessary downloads, and scan thoroughly what they download afterwards)
- For each of the steps I did manually, I removed the associated lines in the script (any step downloading exe or executing the setup for DX for example) but left the rest and re-ran multiple times as I was "debugging"  

Everything else worked well for me (downloads of other software, installation, setup of the system, etc).

**Comment by korjaa** [comment]
Would anyone have the `directx_Jun2010_redist.exe` file available and could confirm the hash?
```
$ sha1sum directx_Jun2010_redist.exe 
f8f1217f666bf2f6863631a7d5e5fb3a8d1542df  directx_Jun2010_redist.exe

$ sha256sum directx_Jun2010_redist.exe 
8746ee1a84a083a90e37899d71d50d5c7c015e69688a466aa80447f011780c0d  directx_Jun2010_redist.exe
```

I'm not looking for absolute truth with utmost certainty, just hoping if you had the file and could chime in if you think the sha256sum for that file should be the one mentioned above.

**Comment by korjaa** [comment]
Correct or not, that DirectX redist did fix my Fallout 76 launch issue :+1:

**Comment by TheAlphaR** [comment]
what about working this out on google cloud what can I do about it?

**Comment by jamesstringerparsec** [comment]
It seems Microsoft has restored some files to their website and the Xbox 360 driver I found at a different official Microsoft location  and updated the script to reflect that.
