### ISSUE TITLE
-15000 Error from Parsec, Host encoder failed

### ISSUE THREAD

**Issue by ocaflo** [parsec-cloud/Parsec-Cloud-Preparation-Tool#69]
Hi all, I know what this code means, but I have already updated the drivers manually and it still doesnt work.. any hint on how to solve this pelase?
Thx!
Oscar.

**Comment by jamesstringerparsec** [comment]
You've provided a serious lack of detail, which makes it impossible for anyone to help you.  This script supports many different cloud providers and many different GPU's, each with their own licensing method.  You need to be more specific.

**Comment by sayaknaiya** [comment]
I am having the same issue. First of all, it is 1360*768 resolution, then when I tried using windows P to different windows, it is showing host encoder failed. I have used the code @jamesstringerparsec  you provided before.. and it worked correctly. But now it is having these problems... Please help us.
I am using G4DN.xlarge instance
