### ISSUE TITLE
Support Paperspace P6000 cards

### ISSUE THREAD

**Issue by mandrean** [parsec-cloud/Parsec-Cloud-Preparation-Tool#70]
Right now the tool only supports the P4000s and P5000s, not the P6000s.

**Comment by jamesstringerparsec** [comment]
I didn't add P6000 because those instance types from my understanding are only available by special request.  In addition, the graphics driver is already installed on Paperspace machines..

**Comment by korjaa** [comment]
At least for now P6000 was available for me to create. I don't remember requesting it specifically. I'm a small scale user, single instance, occasional gaming.
