### ISSUE TITLE
Xbox 360 controller driver link broken

### ISSUE THREAD

**Issue by svenvv** [parsec-cloud/Parsec-Cloud-Preparation-Tool#71]
Hello,

It looks like the 360 controller driver needed for server 2019 has a broken link. This (of course) results in controllers not working until these are installed manually.

Currently: http://download.microsoft.com/download/6/9/4/69446ACF-E625-4CCF-8F56-58B589934CD3/Xbox360_64Eng.exe
Unfortunately I have yet to find a new official Microsoft download.

**Comment by jamesstringerparsec** [comment]
This has been resolved after Microsoft deleted this file, I found the driver in a different official Microsoft location.
