### ISSUE TITLE
AWS Cloud GPU Updater Not Working

### ISSUE THREAD

**Issue by DeeLightfull** [parsec-cloud/Parsec-Cloud-Preparation-Tool#72]
Was working in AWS up to 461.40, but does not work with 461.72 driver update.

**Comment by Almaz-KG** [comment]
Hey there!

I'm following this guide to create a [Gaming Rig](https://github.com/keithvassallomt/parsec-aws-automation) and have faced with the same issue and there is a screenshot with the problem

<img width="975" alt="Screen Shot 2021-03-03 at 12 34 51 AM" src="https://user-images.githubusercontent.com/2547372/109718468-6eea9b80-7bb8-11eb-99d1-51606fa36cba.png">

Thanks in advice

**Comment by ozskywalker** [comment]
When you created your user with programmatic access, what role did you grant that user that owns that access/secret key?

**Comment by Almaz-KG** [comment]
Sorry, I'm not good at AWS and I don't know the correct answer.  How can I understand the Role of the given Access/Secret Key?

**Comment by DeeLightfull** [comment]
@ozskywalker I can confirm I have AmazonS3ReadOnlyAccess on the IAM user, which is what AWS says you need to hit their S3 bucket with the drivers. This is now looking like an permissions thing on AWS side, I will ping my AWS contacts to confirm the new driver has the right read permissions.

**Comment by DeeLightfull** [comment]
Got an update from AWS that it should be fixed. Confirmed with my environment with the IAM user with the AmazonS3ReadOnlyAccess role, that things are working again.
