### ISSUE TITLE
Cannot manually trigger Windows Update

### ISSUE THREAD

**Issue by Hoishin** [parsec-cloud/Parsec-Cloud-Preparation-Tool#73]
After installing Parsec with this script, Windows Update cannot be run even manually in settings, or AWS Systems Manager.

Also the script prevents Windows from installing additional language packs.

The logs on AWS Systems Manager when running `AWS-InstallWindowsUpdates`:
```
04/21/2021 02:35:45 UTC | Info | Searching for Windows Updates.
04/21/2021 02:35:58 UTC | Error | Searching for updates resulted in error: Exception from HRESULT: 0x80240438
```

**Comment by jamesstringerparsec** [comment]
The newest version of the script no longer blocks updates.

If you would like to enable an existing install to communicate with Windows update, please delete the following keys.

HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate  DoNotConnectToWindowsUpdateInternetLocations
HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate UpdateServiceURLAlternative
HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate WUServer
HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate WUSatusServer
HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU AUOptions
HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU UseWUServer
