### ISSUE TITLE
Not showing any desktop icons and no window popup

### ISSUE THREAD

**Issue by sayaknaiya** [parsec-cloud/Parsec-Cloud-Preparation-Tool#74]
After following the given code and works.. It installed fine. But after going to my remote desktop through parsec, no desktop icons are showing. Plus when try to open any windows, no window is showing. It is showing in taskbar but not visible in the wholly. 
@jamesstringerparsec  please help me. [](url)
![WhatsApp Image 2021-05-14 at 9 04 29 PM](https://user-images.githubusercontent.com/75042780/118294770-b23a8200-b4f8-11eb-86c8-cd59d2bbf773.jpeg)

**Comment by sayaknaiya** [comment]
I even tried removing all persistant routes. But the problem is still there.

**Comment by jamesstringerparsec** [comment]
You need to read the FAQ at the bottom of the readme.  The solution is there.

https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool
