### ISSUE TITLE
The tool does not complete installation

### ISSUE THREAD

**Issue by Maladril** [parsec-cloud/Parsec-Cloud-Preparation-Tool#76]
Multiple issues present with recent uses:
Auto login doesn't prompt or even exist on the machine folders.
Parsec desktop shortcut is not present.
Parsec is installed but not correctly launched on machine boot.
GPU update ask for a reboot, reboot the machine but then running the tool again prompt for the same update it's supposed to have done before reboot
 
Tried on: 
-Google Cloud Windows server 2016 with desktop experience and NVIDIA P4
-Google Cloud Windows server 2019 with desktop experience and NVIDIA P4

I've done these exact setups multiple times previously but it recently isn't working anymore and can't really seem to find out why.

**Comment by SaikumarChintada** [comment]
hi @Maladril, installing parsec manually worked for me. not sure about other issues.
