### ISSUE TITLE
AWS blank screen on g4dn.xlarge, using latest script

### ISSUE THREAD

**Issue by shoplift0** [parsec-cloud/Parsec-Cloud-Preparation-Tool#77]
Hi im getting a similar  issue on the link below. Currently building it on AWS
https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/issues/37

Tried to reinstall 5-6 times but the issue is still the same, Blank screen and it will show an error 14003.
I got a successful connection only if RDP is launched, but this defeats the purpose of parsec.

Also I have tried to use the windowskey+P arrow down down, but it says "Could not change display topology during a remote session" .

One more think if I launch the nvidia graphics panel, it's only limited to these options ( i cant even see any monitors)
![image](https://user-images.githubusercontent.com/85392344/120887794-742c0c00-c627-11eb-95cd-7065e7a181c4.png)

**Comment by jamesstringerparsec** [comment]
Run below Powershell on the machine to fix this, then reboot.  I have also added this code to the script so any new users will have this issue fixed automatically.

```
$Configpaths  = (dir HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Configuration).pspath 
$connectivitypaths = (dir HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Connectivity).pspath 
foreach ($path in $Configpaths) {
remove-item -Path $path -Recurse
}
foreach ($path in $connectivitypaths){
remove-item -Path $path -Recurse
}
```
