### ISSUE TITLE
Amazon g4dn.4xlarge: Parsec is not launching after installation

### ISSUE THREAD

**Issue by allan-simon** [parsec-cloud/Parsec-Cloud-Preparation-Tool#78]
I'm running on window server 2019 base

and after the installation, regardless if I reboot or not,  parsec is not automatically launching, and trying to launch it manually does nothing 

I only got something if i open chrome, reinstall it manually , and launch while having my RDP session still open, but at the next reboot I'm back to square 1

**Comment by jamesstringerparsec** [comment]
Please start again by deleting that machine, make sure you sign into Parsec before rebooting the machine after running the script and updating your GPU driver.  I have added an additional warning to GPU updater.

**Comment by allan-simon** [comment]
ok thanks, indeed it seems to fix the issue, thanks a lot !
