### ISSUE TITLE
I cannot get the specified 1080p resolution

### ISSUE THREAD

**Issue by wi2liamalpha** [parsec-cloud/Parsec-Cloud-Preparation-Tool#79]
I cannot get the specified 1080p resolution. g4dn.xlarge instance.

I have tried using GPU update but no results

![image](https://user-images.githubusercontent.com/67695658/121989394-43d23380-cdc6-11eb-8a28-84f43b9856a3.png)

**Comment by jamesstringerparsec** [comment]
I'm guessing you launched your instance from an AMI you or someone else created, please read the Q&A section on the front page of this script.
