### ISSUE TITLE
Connecting with Parsec sends me to login screen; password doesn't work 

### ISSUE THREAD

**Issue by invictus2010** [parsec-cloud/Parsec-Cloud-Preparation-Tool#80]
When I try to connect to my AWS g4dn.xlarge instance with Parsec, I'm stuck at this screen. The password I have doesn't work ("incorrect password").
![image](https://user-images.githubusercontent.com/17661001/123720706-b9bcad00-d852-11eb-9cbd-fcffa3565c07.png)

When I connect with RDP, I am able to get right in. Any thoughts on what I may be doing wrong or may have missed?

**Comment by mrmo123** [comment]
I've had issues typing in the long amazon passwords. Try logging in through RDP, then changing the machine password to something simpler, before logging in through Parsec.

**Comment by jamesstringerparsec** [comment]
As user MrMO123 states, make your password shorter and it will be easier to type.
