### ISSUE TITLE
Parsec GPU Cloud updater tool fails on Windows Server 2022

### ISSUE THREAD

**Issue by Leader-board** [parsec-cloud/Parsec-Cloud-Preparation-Tool#84]
No reason to see why it shouldn't, but it gives this error. This is NV6 on Azure.

![image](https://user-images.githubusercontent.com/42085404/133963784-3bc04e20-bc46-4ad2-9720-b187720129f3.png)

**Comment by jamesstringerparsec** [comment]
The readme states the scripts state are compatible with Server 2016 and Server 2019.

I need to spend some time validating Server 2022, but yes it's likely to work...

**Comment by jamesstringerparsec** [comment]
Fixed for new users
