### ISSUE TITLE
PC resolution is at 1920 x 1080 but for some reason upon loading a game it changes to 1366x768.

### ISSUE THREAD

**Issue by JasonLu18** [parsec-cloud/Parsec-Cloud-Preparation-Tool#90]
![Capture](https://user-images.githubusercontent.com/16448112/155826091-9a8ebdf4-cddc-4942-b318-962f74452e5c.PNG)
![capture2](https://user-images.githubusercontent.com/16448112/155826095-e00cd860-9e8f-48b1-8c34-1ccfd9a79940.PNG)
![capture3](https://user-images.githubusercontent.com/16448112/155826097-928b4037-01fe-4855-811d-181070c27d21.PNG)

Hello I've been having issues with getting a game to be in 1920 x 1080p. For some reason the desktop resolution is at the proper resolution, but upon loading into a game it changes into 1366x768. Quitting the game restores the resolution back to 1920 x 1080p. Attempting to use the GPU updater results in 1280x1024 resolution when attempting to use 1920 x 1080p. I know this has been a past issue with incorrect resolutions for 1080p, is their a clean fix to this?

**Comment by korjaa** [comment]
For me, any resolution issue has always been about GPU driver/license issue.

I can see you have EC2 shortcuts in your desktop, so I would start double checking the guide in here https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html.

For remote gaming, you are interested in the "gaming driver" and also the "GridSwCert.txt" license file. Make sure the registry entries are correct and the file exists.

**Comment by Nyxlyzers** [comment]
I have a similar issue, my resolution is set to 4K, but my games open with the maximum resolution of 1366x768. The desktop is at 4K, but the game isn't. My driver is correctly licensed and I'm using Moonlight.

**Comment by Nyxlanders** [comment]
> For me, any resolution issue has always been about GPU driver/license issue.
> 
> I can see you have EC2 shortcuts in your desktop, so I would start double checking the guide in here https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html.
> 
> For remote gaming, you are interested in the "gaming driver" and also the "GridSwCert.txt" license file. Make sure the registry entries are correct and the file exists.

I have a similar issue, my resolution is set to 4K, but my games open with the maximum resolution of 1366x768. The desktop is at 4K, but the game isn't. My driver is correctly licensed and I'm using Moonlight.
